spring.data.mongodb.auto-index-creation=true
spring.mongodb.uri=mongodb+srv://eshashidhar2000_db_user:5Pao2ummSkpzC6ZB@erripuvvulu.rapw5tv.mongodb.net/lovemeter?retryWrites=true&w=majority&appName=erripuvvulu
server.port=8080
